const date = new Date()
const correctFormat = (date: number) => date < 10 ? '0' + date.toString() : date
const currentDate = correctFormat(date.getDate()) + '.' + correctFormat(date.getMonth()) + '.' + date.getFullYear()
const controlDate = correctFormat(date.getDate() + 5) + '.' + correctFormat(date.getMonth()) + '.' + date.getFullYear()

function getRandomInt(max: number) {
  return Math.floor(Math.random() * max);
}

export const incidents = [
  {
    id: 1,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Низкий',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 10,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 2,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Низкий',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 39,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 3,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Низкий',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 22,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 4,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Средний',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 91,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 5,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Средний',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 120,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 6,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Высокий',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 290,
    creationDate: currentDate,
    decisionTargetDate: controlDate,
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 7,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Критический',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 420,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 8,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Критический',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 310,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
  {
    id: 9,
    name: 'IM' + getRandomInt(999999),
    firstPriority: 'Широкомасштабный',
    param: 'authorization_problem_access',
    subSystem: 'Авторизация',
    errors: 550,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
    description: '',
  },
];
